allowBuilds:
  esbuild: set this to true or false
  tree-sitter: set this to true or false
  tree-sitter-c: set this to true or false
  tree-sitter-go: set this to true or false
  tree-sitter-java: set this to true or false
  tree-sitter-javascript: set this to true or false
  tree-sitter-python: set this to true or false
  tree-sitter-rust: set this to true or false
