import { isChangelogGenre } from "./admit.js";
import { activeTodos, estimateTokens } from "../store/brain-logic.js";

const SUMMARY_MAX_TOKENS = 400;
const STUCK_LIMIT = 3;
const START_HERE_LIMIT = 5;

export function truncateSummaryToTokens(text, maxTokens) {
  const raw = String(text || "").trim();
  if (!raw) return "";
  if (estimateTokens(raw) <= maxTokens) return raw;
  const parts = raw.split(/(?<=[。！？.!?])\s*/).filter(Boolean);
  let acc = "";
  const suffix = "（摘要已截断）";
  for (const part of parts) {
    const next = acc + part;
    if (estimateTokens(next + suffix) > maxTokens) break;
    acc = next;
  }
  if (!acc) {
    let cut = raw;
    while (cut.length > 8 && estimateTokens(cut + suffix) > maxTokens) {
      cut = cut.slice(0, Math.floor(cut.length * 0.85));
    }
    acc = cut.trim();
  }
  return acc.replace(/\s+$/, "") + suffix;
}

function qualifiedSummary(text) {
  const summary = String(text || "").trim();
  if (!summary) return "";
  if (isChangelogGenre("", summary) || isChangelogGenre(summary, summary)) return "";
  return summary;
}

function latestQualifiedSummaryEvent(timeline) {
  const summaries = (timeline || [])
    .filter((e) => e && e.eventType === "session_summary")
    .map((e) => Object.assign({}, e, { summary: qualifiedSummary(e.summary) }))
    .filter((e) => e.summary)
    .sort((a, b) => (b.occurredAt || 0) - (a.occurredAt || 0));
  return summaries.length ? summaries[0] : null;
}

export function latestDisposedSessionSummary(timeline) {
  const event = latestQualifiedSummaryEvent(timeline);
  return event ? event.summary : "";
}

export function isArchitectureStale(brain) {
  if (!brain) return false;
  if (brain.architectureStale === true) return true;
  if (brain.architecture && brain.architecture.stale === true) return true;
  if (brain.project && brain.project.architectureStale === true) return true;
  return false;
}

function keyFilePaths(architecture) {
  const list = (architecture && architecture.keyFiles) || [];
  return list.map((item) => {
    if (typeof item === "string") return item.replace(/\\/g, "/");
    return String((item && item.path) || "").replace(/\\/g, "/");
  }).filter(Boolean);
}

function flowEndpointFiles(architecture) {
  const flows = (architecture && architecture.runtimeFlows) || [];
  const out = [];
  for (const flow of flows) {
    const steps = (flow && flow.steps) || [];
    if (!steps.length) continue;
    const first = steps[0] && steps[0].file;
    const last = steps[steps.length - 1] && steps[steps.length - 1].file;
    if (first) out.push(String(first).replace(/\\/g, "/"));
    if (last && last !== first) out.push(String(last).replace(/\\/g, "/"));
  }
  return out;
}

function asRelPath(path) {
  if (typeof path === "string") return path.replace(/\\/g, "/").replace(/^\.\//, "");
  if (path && typeof path === "object") {
    return String(path.path || "").replace(/\\/g, "/").replace(/^\.\//, "");
  }
  return "";
}

function isSourcePath(item) {
  const p = asRelPath(item);
  if (!p) return false;
  const type = item && typeof item === "object" ? String(item.type || "") : "";
  if (type === "script") return false;
  if (/^(npm|pnpm|yarn|npx|node)\s/i.test(p)) return false;
  if (/\s/.test(p) && !/[\\/]/.test(p)) return false;
  return true;
}

function uniquePaths(paths, limit) {
  const seen = new Set();
  const out = [];
  for (const path of paths) {
    const item = typeof path === "string" ? { path } : path;
    if (!isSourcePath(item)) continue;
    const p = asRelPath(item);
    if (!p || seen.has(p)) continue;
    seen.add(p);
    out.push(p);
    if (out.length >= limit) break;
  }
  return out;
}

// scanner 在没有 README 可用时会写死这句占位符；它不是项目定位，宁可留空也别当介绍展示。
const DESCRIPTION_PLACEHOLDER = /^auto-generated by dsh-project-brain$/i;

function purposeLine(brain) {
  const project = brain.project || {};
  const overview = (brain.architecture && brain.architecture.overview) || {};
  const fromArch = String(overview.purpose || "").trim();
  const rawDesc = String(project.description || "").replace(/\s+/g, " ").trim();
  const fromDesc = DESCRIPTION_PLACEHOLDER.test(rawDesc) ? "" : rawDesc;
  return (fromArch || fromDesc).slice(0, 300);
}

function startHere(brain, stale) {
  const project = brain.project || {};
  const entries = (Array.isArray(project.entrypoints) ? project.entrypoints : []).filter(isSourcePath);
  if (stale) return uniquePaths(entries, 2);
  return uniquePaths(entries.concat(keyFilePaths(brain.architecture), flowEndpointFiles(brain.architecture)), START_HERE_LIMIT);
}

function stuckTodos(todos) {
  const active = activeTodos(todos || []);
  const inProgress = active.filter((t) => t && t.status === "in_progress");
  const rest = active.filter((t) => t && t.status !== "in_progress");
  return inProgress.concat(rest).slice(0, STUCK_LIMIT).map((t) => ({
    id: t.id,
    title: t.title,
    status: t.status,
    priority: t.priority,
  }));
}

const DAY_MS = 86_400_000;
const RECENT_WORK_STALE_DAYS = 30;

function ageDays(at, now) {
  if (!at) return 0;
  return Math.max(0, Math.floor((now - at) / DAY_MS));
}

// 「最近做什么」不带时间会骗人：LLM 关掉几周后，第一屏还在拿旧摘要冒充近况。
function recentWorkAgeLabel(at, now) {
  if (!at) return "";
  const days = ageDays(at, now);
  if (days <= 0) return "今天";
  if (days > RECENT_WORK_STALE_DAYS) return days + " 天前，可能已过时";
  return days + " 天前";
}

function recentWorkFrom(brain, now) {
  const event = latestQualifiedSummaryEvent(brain.timeline);
  const fromSummary = truncateSummaryToTokens(event ? event.summary : "", SUMMARY_MAX_TOKENS);
  if (fromSummary) {
    const at = Number(event && event.occurredAt) || 0;
    return {
      recentWork: fromSummary,
      recentWorkSource: "session_summary",
      recentWorkAt: at,
      recentWorkStale: Boolean(at) && ageDays(at, now) > RECENT_WORK_STALE_DAYS,
    };
  }
  const inProgress = stuckTodos(brain.todos).filter((t) => t.status === "in_progress");
  if (inProgress.length) {
    return {
      recentWork: inProgress.map((t) => "进行中 " + t.title).join("；"),
      recentWorkSource: "todo",
      recentWorkAt: 0,
      recentWorkStale: false,
    };
  }
  return { recentWork: "", recentWorkSource: "none", recentWorkAt: 0, recentWorkStale: false };
}

function briefingMarkdown({ stale, purpose, startHere: files, recentWork, recentWorkAt, now }) {
  const lines = [];
  lines.push("### 这是什么");
  lines.push(purpose || "（暂无项目定位，重扫可由架构分析补全）");
  lines.push("");
  lines.push("### 最近做什么");
  if (recentWork) {
    const age = recentWorkAgeLabel(recentWorkAt, now);
    lines.push(recentWork.replace(/\n+/g, " ") + (age ? "（" + age + "）" : ""));
  } else {
    lines.push("（暂无会话摘要）");
  }
  lines.push("");
  lines.push("### 从哪改");
  if (stale) lines.push("架构可能过期，关键文件按扫描入口降级。");
  if (files.length) {
    for (const f of files) lines.push("- " + f);
  } else {
    lines.push("- （暂无入口）");
  }
  return lines.join("\n");
}

export function buildProjectBriefing(brain, now = Date.now()) {
  if (!brain || !brain.project || brain.project.__error) {
    return {
      stale: false,
      purpose: "",
      startHere: [],
      stuck: [],
      recentWork: "",
      recentWorkSource: "none",
      recentWorkAt: 0,
      recentWorkStale: false,
      markdown: "",
    };
  }
  const stale = isArchitectureStale(brain);
  const purpose = purposeLine(brain);
  const files = startHere(brain, stale);
  const stuck = stuckTodos(brain.todos);
  const recent = recentWorkFrom(brain, now);
  const markdown = briefingMarkdown({
    stale,
    purpose,
    startHere: files,
    recentWork: recent.recentWork,
    recentWorkAt: recent.recentWorkAt,
    now,
  });
  return {
    stale,
    purpose,
    startHere: files,
    stuck,
    recentWork: recent.recentWork,
    recentWorkSource: recent.recentWorkSource,
    recentWorkAt: recent.recentWorkAt,
    recentWorkStale: recent.recentWorkStale,
    markdown,
  };
}
