// project_init / project_rescan Tools
// 走 dsh-tools 的 defineTool（标准通道）
//
// P0.4.1 修复：
//  - project_init 重跑时保留已有 projectId / createdAt（此前每次重新生成）
//  - 写入 timeline.jsonl 事件（init / rescan），SidebarPreview 最近活动有真实数据
//  - 新增 project_rescan 工具（原 project_init 描述里承诺过但一直不存在）
//
// P0.4.2 修复（用户实测反馈）：
//  - 去掉 process.cwd() fallback：tool 在 DSH Desktop 进程下 cwd=安装目录，会扫到 DSH.exe。
//    改为 path 必传（或显式 fail），避免扫错目录。
//  - 写文件用 sandboxPolicy.resolve({mode:'workspace-write'}) 拿宽松 policy，
//    作为参数传给 fs.writeText 第 5 参数。即使默认 mode='read-only' 也能写。
//  - render 容错：value 结构异常时 fallback 显示。

import { defineTool } from "@deepseek-ai/dsh-tools";
import { sanitizeProjectDescription, scanProject } from "./scanner.js";
import { assertSafeProjectPath, brainPath, readJson, writeJson, appendJsonl } from "./host/store/brain-files.js";
import { makeId } from "./host/store/brain-logic.js";
import { resolveProjectPath } from "./host/store/path-resolver.js";
import { buildArchitecture, resolveSessionRoute } from "./host/architecture/analyzer.js";

function emitPreviewChanged(exec, projectPath) {
  try {
    const executor = (exec && exec.ctx) || null;
    if (executor && typeof executor.emit === "function") {
      executor.emit("project_brain/preview.changed", { projectPath: projectPath });
    }
  } catch (e) { /* ignore */ }
}

// 拿一个宽松的沙箱 policy（fs.writeText 第 5 参数）
// P0.4.4 修复：之前用 mode 'workspace-write' 仍然限制在 workspaceRoot
// (插件 fiber 启动时 = dsh-project-brain 自身目录，不随 session 切换)。
// 改用 mode 'danger-full-access' 完全跳过文件路径限制（参考 DSH sandbox 文档：
// "danger-full-access bypasses confinement"）。
// 安全边界：Host 服务需要跨动态 workspace 写入，因此底层 policy 必须放宽；应用层
// 始终让 live Session cwd 优先，并由 assertSafeProjectPath + brainPath 把目标限制到
// 已解析项目的 .project-brain/，拒绝缺失路径、文件系统根目录和路径逃逸。
function resolveWritePolicy(sandboxPolicy) {
  if (!sandboxPolicy) return null;
  try {
    if (typeof sandboxPolicy.resolve === "function") {
      return sandboxPolicy.resolve({ mode: "danger-full-access" });
    }
  } catch (e) { /* fallthrough */ }
  return sandboxPolicy;
}

// 共享扫描 + 写入逻辑
export async function scanAndWrite(fs, sandboxPolicy, args, toolLabel, runtime = {}) {
  const startMs = Date.now();
  // P0.4.2 修复：path 必传（不传直接 fail）。
  // 原先 fallback 到 process.cwd() 会扫到 DSH Desktop 安装目录。
  const explicit = (args && typeof args.path === "string" && args.path.trim()) ? args.path.trim() : null;
  if (!explicit) {
    return {
      ok: false,
      data: {
        error: { code: "E_NO_PATH", message: "path 参数必传（不传会扫到 DSH Desktop 安装目录）" },
        scanDurationMs: Date.now() - startMs,
      },
    };
  }
  let projectPath;
  try {
    projectPath = assertSafeProjectPath(explicit);
  } catch (error) {
    return {
      ok: false,
      data: { error: { code: error.code || "E_UNSAFE_PROJECT_PATH", message: String(error.message || error) }, scanDurationMs: Date.now() - startMs },
    };
  }
  const dryRun = Boolean(args && args.dryRun);

  let scan;
  try {
    scan = await scanProject(fs, projectPath);
  } catch (e) {
    return {
      ok: false,
      data: {
        error: { code: "E_SCAN_FAILED", message: String((e && e.message) || e) },
        scanDurationMs: Date.now() - startMs,
      },
    };
  }

  let existing;
  try {
    existing = await readJson(fs, brainPath(projectPath, "project.json"));
  } catch (e) {
    existing = null;
  }
  const isRescan = Boolean(existing && existing.id);

  let previousArchitecture = null;
  try {
    previousArchitecture = await readJson(fs, brainPath(projectPath, "architecture.json"));
  } catch (e) {}
  const architectureConfig = runtime.getMemoryConfig ? runtime.getMemoryConfig() : {};
  let architecture = null;
  if (architectureConfig.architectureEnabled !== false) {
    try {
      architecture = await buildArchitecture({
        fs,
        projectPath,
        scan,
        previous: previousArchitecture && !previousArchitecture.__error ? previousArchitecture : null,
        config: architectureConfig,
        llm: runtime.getLlm ? runtime.getLlm() : null,
        route: runtime.llmRoute || null,
        getRoute: runtime.getLlmRoute || null,
        sessionId: runtime.sessionId || null,
      });
    } catch (e) {
      architecture = { error: { code: e.code || "ARCHITECTURE_FAILED", message: String((e && e.message) || e) } };
    }
  }

  const now = Date.now();
  const projectName = scan.projectName || projectPath.split(/[\\/]/).filter(Boolean).pop() || "untitled";
  const existingDescription = sanitizeProjectDescription(existing && existing.description);
  const scannedDescription = sanitizeProjectDescription(scan.description);
  const projectData = {
    id: isRescan ? existing.id : makeId("brain", now),
    name: projectName,
    rootPath: projectPath,
    description: (existingDescription && existingDescription !== "Auto-generated by dsh-project-brain")
      ? existingDescription
      : (scannedDescription || "Auto-generated by dsh-project-brain"),
    techStack: scan.techStack,
    languages: scan.languages,
    tooling: scan.tooling || [],
    size: { files: scan.fileCount },
    entrypoints: scan.entrypoints,
    topLevel: scan.topLevel,
    directoryMap: (existing && existing.directoryMap) || [],
    createdAt: isRescan ? existing.createdAt : now,
    updatedAt: now,
    lastScannedAt: now,
  };

  if (!dryRun) {
    // P0.4.2 修复：显式拿 workspace-write policy，传给 fs.writeText 第 5 参数。
    const writePolicy = resolveWritePolicy(sandboxPolicy);
    const wroteProject = await writeJson(fs, brainPath(projectPath, "project.json"), projectData, writePolicy);
    if (!wroteProject) {
      return {
        ok: false,
        data: {
          error: { code: "E_WRITE_FAILED", message: "failed to write " + brainPath(projectPath, "project.json") + "（可能是 sandbox 拒绝）" },
          scanDurationMs: Date.now() - startMs,
        },
      };
    }
    if (architecture && !architecture.error) {
      const wroteArchitecture = await writeJson(fs, brainPath(projectPath, "architecture.json"), architecture, writePolicy);
      if (!wroteArchitecture) {
        architecture = { error: { code: "ARCHITECTURE_WRITE_FAILED", message: "架构数据写入失败，项目基础扫描仍已完成" } };
      }
    }
    try {
      await appendJsonl(fs, brainPath(projectPath, "timeline.jsonl"), {
        id: makeId("evt", now),
        title: isRescan ? "完成重扫（" + toolLabel + "）" : "完成 project_init 扫描",
        eventType: isRescan ? "rescan" : "init",
        occurredAt: now,
        detail: "languages=" + (Object.keys(scan.languages).join("/") || "none") + " files=" + scan.fileCount +
          (architecture && !architecture.error ? " modules=" + architecture.stats.modules + " edges=" + architecture.stats.edges + " architecture=" + architecture.source : ""),
      }, writePolicy);
    } catch (e) {
      // timeline 写入失败不阻塞整体成功
    }
  }

  return {
    ok: true,
    data: {
      projectId: projectData.id,
      name: projectName,
      isRescan: isRescan,
      createdAtPreserved: isRescan,
      scanDurationMs: Date.now() - startMs,
      stats: {
        files: scan.fileCount,
        languages: scan.languages,
        techStack: scan.techStack,
        tooling: scan.tooling || [],
        entrypoints: scan.entrypoints,
        topLevel: scan.topLevel,
      },
      partial: Boolean(architecture && architecture.error),
      architecture: architecture && !architecture.error ? {
        generated: true,
        changed: architecture.changed,
        version: architecture.version,
        source: architecture.source,
        modules: architecture.stats.modules,
        edges: architecture.stats.edges,
        llm: architecture.llm,
      } : {
        generated: false,
        error: architecture && architecture.error ? architecture.error : null,
      },
      dryRun: dryRun,
    },
  };
}

// output schema 简化为只声明 ok + data (additionalProperties: true)
// 让 fail/success 都通过 schema 校验，避免框架吞 data 字段
// v0.3.8：显式声明 ok/code/message，错误路径返回不再被拒（顶层 { ok:false, code, message }）
const baseOutputSchema = {
  type: "object",
  additionalProperties: true,
  properties: {
    ok: { type: "boolean" },
    data: { type: "object", additionalProperties: true },
    code: { type: "string" },
    message: { type: "string" },
  },
};

const pathParam = { type: "string", description: "项目根路径（可选；默认从当前 DSH Session 的 workspace 自动解析）" };
const dryRunParam = { type: "boolean", description: "仅预览，不写文件（默认 false）" };

function executionRoute(exec) {
  if (!exec) return null;
  return resolveSessionRoute(exec.session)
    || resolveSessionRoute(exec.currentSession)
    || resolveSessionRoute(exec.agent && exec.agent.session)
    || resolveSessionRoute(exec.agent)
    || resolveSessionRoute(exec.ctx && exec.ctx.session);
}

function executionSessionId(exec) {
  return exec && (exec.sessionId
    || (exec.session && exec.session.id)
    || (exec.agent && exec.agent.sessionId)
    || (exec.agent && exec.agent.session && exec.agent.session.id)) || null;
}

function buildInitTool({ fs, sandboxPolicy, getMemoryConfig, getLlm }) {
  return defineTool({
    name: "project_init",
    description:
      "dsh-project-brain: 扫描目标项目、识别技术栈、生成 .project-brain/project.json（含 timeline init 事件）。" +
      "首次访问新项目时调用一次；重复调用安全（保留 projectId/createdAt）；增量更新用 project_rescan。" +
      "默认自动使用当前 DSH Session 的 workspace；仅 CLI/旧宿主需要显式传 path。",
    parameters: { path: pathParam, dryRun: dryRunParam },
    // 关键修复（P0.4.3）：render 必须嵌套在 output 里（dsh-tools 0.1.0-rc.x 期望
    // options.output.render）。之前误把 render 放 top-level，导致 userRender 变 undefined，
    // 框架调用时抛 "userRender is not a function"。
    output: { schema: baseOutputSchema, render: (_args, value) => renderProjectTool(value, "project init") },
    async execute(args, exec) {
      try {
        const projectPath = resolveProjectPath(args, exec, sandboxPolicy);
        if (projectPath === ".") {
          return { ok: false, data: { error: { code: "E_NO_PATH", message: "无法从当前 Session 解析 workspace 路径" } } };
        }
        const resolvedArgs = Object.assign({}, args || {}, { path: projectPath });
        const result = await scanAndWrite(fs, sandboxPolicy, resolvedArgs, "project_init", {
          getMemoryConfig,
          getLlm,
          llmRoute: executionRoute(exec),
          getLlmRoute: () => executionRoute(exec),
          sessionId: executionSessionId(exec),
        });
        if (result.ok && !(args && args.dryRun)) {
          emitPreviewChanged(exec, projectPath);
        }
        return result;
      } catch (e) {
        return {
          ok: false,
          data: { error: { code: "E_SCAN_FAILED", message: String((e && e.message) || e) } },
        };
      }
    },
  });
}

function buildRescanTool({ fs, sandboxPolicy, getMemoryConfig, getLlm }) {
  return defineTool({
    name: "project_rescan",
    description:
      "dsh-project-brain: 重扫已有 .project-brain 的项目并增量刷新 project.json" +
      "（保留 projectId/createdAt/记忆/待办，只更新技术栈/入口/语言统计），追加 timeline rescan 事件。" +
      "项目结构变化后调用；默认自动使用当前 DSH Session 的 workspace。",
    parameters: { path: pathParam, dryRun: dryRunParam },
    output: { schema: baseOutputSchema, render: (_args, value) => renderProjectTool(value, "rescan") },
    async execute(args, exec) {
      try {
        const projectPath = resolveProjectPath(args, exec, sandboxPolicy);
        if (projectPath === ".") {
          return { ok: false, data: { error: { code: "E_NO_PATH", message: "无法从当前 Session 解析 workspace 路径" } } };
        }
        const resolvedArgs = Object.assign({}, args || {}, { path: projectPath });
        const result = await scanAndWrite(fs, sandboxPolicy, resolvedArgs, "project_rescan", {
          getMemoryConfig,
          getLlm,
          llmRoute: executionRoute(exec),
          getLlmRoute: () => executionRoute(exec),
          sessionId: executionSessionId(exec),
        });
        if (result.ok && !(args && args.dryRun)) {
          emitPreviewChanged(exec, projectPath);
        }
        return result;
      } catch (e) {
        return {
          ok: false,
          data: { error: { code: "E_SCAN_FAILED", message: String((e && e.message) || e) } },
        };
      }
    },
  });
}

function renderProjectTool(value, toolLabel) {
  // 容错：value 可能不是 {ok, data} 结构（比如 schema 校验失败时框架剥了 data）
  if (!value || typeof value !== "object") {
    return [{ type: "text", text: `dsh-project-brain: ${toolLabel} FAILED - non-object result: ` + String(value) }];
  }
  if (value.ok) {
    const d = value.data || {};
    if (d.error) {
      return [{ type: "text", text: `dsh-project-brain: ${toolLabel} FAILED - ${d.error.code}: ${d.error.message}` }];
    }
    return [
      { type: "text", text: `dsh-project-brain: ${toolLabel} OK` },
      { type: "text", text: `  projectId: ${d.projectId}` },
      { type: "text", text: `  name: ${d.name}` },
      { type: "text", text: `  isRescan: ${d.isRescan}（id/createdAt 已保留）` },
      { type: "text", text: `  scanDurationMs: ${d.scanDurationMs}` },
      { type: "text", text: `  stats: ${JSON.stringify(d.stats)}` },
      { type: "text", text: `  architecture: ${JSON.stringify(d.architecture || {})}` },
      ...(d.dryRun ? [{ type: "text", text: "  (dry run)" }] : []),
    ];
  }
  // value.ok 是 false，但 value.data 可能 undefined（框架剥了）
  if (value.data && value.data.error) {
    return [{ type: "text", text: `dsh-project-brain: ${toolLabel} FAILED - ${value.data.error.code}: ${value.data.error.message}` }];
  }
  return [{ type: "text", text: `dsh-project-brain: ${toolLabel} FAILED - ` + JSON.stringify(value) }];
}

// 向后兼容旧导出
export function buildProjectInitTool(opts) { return buildInitTool(opts); }
export function buildProjectRescanTool(opts) { return buildRescanTool(opts); }
